### ISSUE TITLE
Fail to work after late Oct maintenance 

### ISSUE THREAD

**Issue by Yefee** [NCAR/ncar-jobqueue#101]
Hi all, 

Thanks for building the great package!

After the late Oct maintenance, the package doesn't work anymore. Below is my call and error message. Any ideas? Thanks!

I noticed in other threads that you are going to retire this package. I am wondering if there is any replacement? 

![CleanShot 2023-11-09 at 11 43 54](https://github.com/NCAR/ncar-jobqueue/assets/6420873/9e28f6ad-5a04-44de-8077-9a9b4cc90d99)

**Comment by dcherian** [comment]
See https://github.com/NCAR/ncar-jobqueue/commit/2e0bed31c064a96324affdcea2dc02cd3ed9e515

CHange your `ncar-jobqueue.yaml` similarly

**Comment by Yefee** [comment]
> See [2e0bed3](https://github.com/NCAR/ncar-jobqueue/commit/2e0bed31c064a96324affdcea2dc02cd3ed9e515)
> 
> CHange your `ncar-jobqueue.yaml` similarly

I modified the configuration in the yaml file within the python package directory, but I am still encountering the "ib0" error.

Will the yaml file be copied to a specific location in the $USER directory during installation, and do I need to make changes to it?

Thanks!

**Comment by Yefee** [comment]
> > See [2e0bed3](https://github.com/NCAR/ncar-jobqueue/commit/2e0bed31c064a96324affdcea2dc02cd3ed9e515)
> > CHange your `ncar-jobqueue.yaml` similarly
> 
> I modified the configuration in the yaml file within the python package directory, but I am still encountering the "ib0" error.
> 
> Will the yaml file be copied to a specific location in the $USER directory during installation, and do I need to make changes to it?
> 
> Thanks!

Found it. The yaml file is located at: ~/.config/dask
