### ISSUE TITLE
timeout on server starting

### ISSUE THREAD

**Issue by karenamckinnon** [NCAR/ncar-jobqueue#34]
I've just pip installed ncar-jobqueue==2020.12.4.

In a jupyter notebook on Casper, I have:

```
from ncar_jobqueue import NCARCluster
from dask.distributed import Client
cluster = NCARCluster()
cluster
```

After logging in and selecting the parameters for my cluster, the server starting up page hangs at "Spawning server" until it times out. 

Thoughts on what may be going wrong? Thanks!

**Comment by andersy005** [comment]
👋 @karenamckinnon, 

When you get a chance, can you post here a screenshot of the parameters you are using to launch the job?

<img width="1140" alt="Screen Shot 2020-12-07 at 9 46 43 AM" src="https://user-images.githubusercontent.com/13301940/101379142-2d747980-3871-11eb-8193-57b1661e75fa.png">

**Comment by karenamckinnon** [comment]
![Screen Shot 2020-12-07 at 9 51 06 AM](https://user-images.githubusercontent.com/8631291/101379707-cd320780-3871-11eb-916b-d720b70410ce.png)
I just left them at the default values as a test.

**Comment by andersy005** [comment]
Great... Everything looks good. I think the job scheduler on casper may have been busy during your last job submission. My recommendation is to try again, and if it fails again, reduce the walltime to an hour and see if you get through the queue.

**Comment by karenamckinnon** [comment]
Is this scheduler going through a different process than what is happening if I request nodes from the command line? For example, I have no trouble with

`execdav -t 02:00:00 -n 2  --account p93300313`

from a login node.

**Comment by matt-long** [comment]
@karenamckinnon, the scheduler is submitting batch jobs via Slurm for the Dask workers. You can check on the status of these jobs using `squeue`.

Note that several default arguments to `NCARCluster` are set in a config file in your home directory:
~/.config/dask/ncar-jobqueue.yaml

**Comment by karenamckinnon** [comment]
I see. I think something may be going wrong with the submission of the batch job. Here is the output from my `squeue`

```
(NPL) mckinnon@casper-login1:~/exploratory/SMILEs$ squeue -u $USER
             JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON) 
           6256786       dav     srun mckinnon  R       6:16      1 casper01 
```

The currently running job is the interactive job I started from a login node to then launch my jupyter notebook (i.e. my jupyter notebook is running off of `casper01`).

**Comment by matt-long** [comment]
I would guess that the work jobs are being rejected. After you create the cluster, try:
```
print(cluster.job_header)
```
Does it look like a valid Slurm submission?

**Comment by andersy005** [comment]
I may have misread this issue because I thought the issue was happening when launching Jupyter Lab via jupyterhub.ucar.edu/dav

**Comment by matt-long** [comment]
I am also somewhat confused by 
> After logging in and selecting the parameters for my cluster, the server starting up page hangs at "Spawning server" until it times out.

Logging in where?

**Comment by karenamckinnon** [comment]
Let me try to be more clear about what I am doing, and let me know if I should go through a different process.

1. Log onto a casper login node
**2. Launch an interactive job on a compute node
3. Start a jupyter notebook via start-notebook
4. In my notebook, write
```
from ncar_jobqueue import NCARCluster
from dask.distributed import Client
cluster = NCARCluster()
cluster
```
5. The output is:
![Screen Shot 2020-12-07 at 10 26 30 AM](https://user-images.githubusercontent.com/8631291/101383711-b641e400-3876-11eb-9e67-2886b8211e62.png)
I then click on the dashboard link, which (the first time) asked me to authenticate via CIT. It then brings me to this page:
![Screen Shot 2020-12-07 at 10 27 32 AM](https://user-images.githubusercontent.com/8631291/101383815-d96c9380-3876-11eb-933a-e81b71385f3c.png)
6. I put in my parameters for the cluster as above, and the page hangs with "Spawning server"

**Step (2) would be the usual approach I would take to do compute on jupyter notebooks without dask. Should I just be launching a notebook from a login node if I'm using dask, since I'm opening up a compute cluster in the notebook?

Is there another approach I should be taking?

**Comment by matt-long** [comment]
Ah, this is because that dashboard link is not set correctly for what you are doing. @andersy005 can help sort that out. 

When you click that link, you are essentially starting a JLab session! Not the dask workers.

I suggest using jupyterhub.ucar.edu (i.e., step 1).  It is pretty robust these days. Then the dashboard link would be correct!

**Comment by karenamckinnon** [comment]
Got it. @andersy005 , I was aiming to follow the Casper Usage case in the README, but perhaps the intention was to have that use case run on the jupyterhub.

**Comment by matt-long** [comment]
There is an implicit assumption that the user is running from jupterhub.ucar.edu:
https://github.com/NCAR/ncar-jobqueue/blob/037f0d07d8e9d354d42e0d5bc989f1d50987485a/ncar_jobqueue/cluster.py#L26

Perhaps we should make this more clear in the README and provide instructions for
```python
dask.config.set({'distributed.dashboard.link' : '/proxy/{port}/status'})
```

**Comment by karenamckinnon** [comment]
Thanks @andersy005 . I've tried the updated commands as you suggest, and it does look like the cluster is running as expected:
![Screen Shot 2020-12-07 at 2 55 16 PM](https://user-images.githubusercontent.com/8631291/101410250-5100e980-389c-11eb-8d97-fb893bc5a450.png)
but when I click on the Dashboard link, I get a `404 Not Found`. The browser is linking to `http://localhost:8888/proxy/41436/status` (my notebook is running at `http://localhost:8888/`).

**Comment by andersy005** [comment]
:( is your notebook running from the JupyterHub or are you still using the `start-notebook` command via SSH?

**Comment by karenamckinnon** [comment]
This is running via the `start-notebook` command. We did seem to solve the JupyterHub problem, but figured it would still be good to solve this one if we can.

**Comment by andersy005** [comment]
Great... We have two options


- Option 1) Install Jupyter-server-proxy package in your NPL environment. This will allow us to access the dashboard session using the proxy running from the jupyter notebook:

	```python
	pip install jupyter-server-proxy --user
	```

	With this option, I expect following the dashboard link to work as expected. I could be wrong though :) 

- Option 2) Change this line `dask.config.set({'distributed.dashboard.link' : '/proxy/{port}/status'})` to `dask.config.set({'distributed.dashboard.link' : '/{port}/status'})`. Then, retrieve the dashboard port number from the notebook and set up a new ssh tunnel (in a new terminal) for the dashboard traffic. 

	For instance, from the example above, you may get the following dashboard info **Dashboard: /41436/status**. The port number is **41436**. So, the SSH tunnel would look like this: `ssh -N -L 41436:HOSTNAME:41436 YOURUSERNAME@casper.ucar.edu` (Replace `HOSTNAME` with the name of the casper node your notebook is running from). If everything is working properly, point your browser to `http://localhost:41436`


In my opinion, Option 2) is too complicated. So, I recommend giving Option 1) a try...

**Comment by karenamckinnon** [comment]
Option 1 didn't work for me, but Option 2 did. Thanks for your replies, and hopefully this may be helpful for future users as well.
