### ISSUE TITLE
Casper switch to PBS

### ISSUE THREAD

**Issue by dcherian** [NCAR/ncar-jobqueue#40]
https://github.com/NCAR/ncar-jobqueue/blob/123fe2bce463ac69f948f3f5c3a4ea7dd3f9027f/ncar_jobqueue/cluster.py#L24

Should switch to PBSCluster

**Comment by matt-long** [comment]
Since the cluster will always be PBSCluster, we could consider retiring the package. However, this would leave existing codes inoperable on the new system. Also, we may want to curate defaults appropriate to each system.

**Comment by dcherian** [comment]
`dashboard_link` is a nice one to configure automatically.
