### ISSUE TITLE
dashboard_link doesn't print correctly

### ISSUE THREAD

**Issue by mnlevy1981** [NCAR/ncar-jobqueue#49]
After updating to v2021.04.14 and setting up a PBS cluster on casper, when I run

```py3
print(f"dashboard_link={cluster.dashboard_link}")
```

the output is

```
dashboard_link=https://jupyterhub.hpc.ucar.edu/stable/user/mlevy/proxy/{port}/status
```

Rather than actually filling in the value of `port`:

![jobqueue issue](https://user-images.githubusercontent.com/4297161/114896314-77e0a680-9dcd-11eb-8f99-7ad28b180296.png)

**Comment by andersy005** [comment]
@mnlevy1981, can you confirm that you are actually using `ncar-jobqueue` to create the cluster? From your screenshot, I am noticing that you are using `dask_jobqueue` directly. 


Things seem to be working fine on my end: 

<img width="802" alt="Screen Shot 2021-04-15 at 9 47 47 AM" src="https://user-images.githubusercontent.com/13301940/114898777-a5c6ea80-9dcf-11eb-886e-02d166e7c8c0.png">

**Comment by mnlevy1981** [comment]
@andersy005 you're right - I had switched from `dask_jobqueue` to `ncar_jobqueue` last night but that didn't work because pip installed a March release of this package. Then I switched back this morning because the caffeine hadn't kicked in yet... after verifying I got yesterday's release installed and was actually calling it, it looks this package is working correctly :)

![jobqueue issue 2](https://user-images.githubusercontent.com/4297161/114902688-4cf95100-9dd3-11eb-916b-a549e7d1fe6b.png)
