### ISSUE TITLE
adaptive cluster releasing workers too soon.

### ISSUE THREAD

**Issue by dcherian** [NCAR/ncar-jobqueue#8]
I am using ncar_jobqueue to spin up a cluster on DAV.

I tend to use `cluster.adapt(minimum=2, maximum=36)` or something similar

I find that the cluster scales up as expected but then releases 34 workers as soon as the computation is done. This even happens within code that looks like
```
for something:
    do_something_in_parallel; # cluster spins up here
    print_to_screen 
    # cluster releases workers here
```
Here distributed requests a new set of workers and then releases them at each iteration which makes it really slow for no good reason.

Is there an argument I can specify so that the workers are only released after say 10 minutes of idle time?

**Comment by andersy005** [comment]
@dcherian, 

Per the API documenation: http://distributed.dask.org/en/latest/api.html#adaptive, you can specify additional arguments such as `target_duration`, `interval`, `wait_count`. 

```python
cluster.adapt(minimum=2, maximum=36, target_duration=..., interval=..., wait_count=...)
```

I am not 100% sure if this addresses your issue ( I've not tried it myself). Let me know if this helps.

**Comment by dcherian** [comment]
Unfortunately "target_duration" only seems to control how quickly the cluster is spun up. 
My work around for now is to scale using `cluster.scale`

**Comment by andersy005** [comment]
You are right. There's now clear way of keep workers around with `cluster.adapt()`. I asked this same question on Gitter: https://gitter.im/dask/dask

I will get back to you once I have an answer. This may be a missing feature

**Comment by dcherian** [comment]
=) Thanks!

**Comment by andersy005** [comment]
@dcherian,

It appears that `wait_count` might do what we're looking for. It determines how often a worker is to be recommended for shutdown before it actually goes. Interval between new recommendations defaults to 1000 milliseconds. So for a minute choose `wait_count=60`, for 10 minutes, choose `wait_count=600`.

**Comment by dcherian** [comment]
Thanks @andersy005 . That seems to work!

**Comment by andersy005** [comment]
Glad to hear that this addresses the issue, @dcherian! Feel free to close this issue.
