### ISSUE TITLE
Add support for Hobart cluster 

### ISSUE THREAD

**Issue by andersy005** [NCAR/ncar-jobqueue#9]
Since Hobart uses the PBS job scheduler, it would be nice to add it to the list of supported clusters in ncar_jobqueue.

**Comment by matt-long** [comment]
Perhaps we should move the dask jobqueue.yaml config to this repo? We need a good way to set user defaults for each system. On Cheyenne, SLURM and PBS are independent, but to support Hobart and Cheyenne, we'll need two PBS settings.

**Comment by andersy005** [comment]
As @matt-long pointed out in https://github.com/NCAR/ncar-pangeo-tutorial/issues/14, even though Hobart uses PBS scheduler, hobart's configuration is different from Cheyenne's. Therefore, we need to set appropriate defaults for specific to Hobart. 

Because Dask makes it very easy to extend its configurations via [downstream libraries](https://docs.dask.org/en/latest/configuration.html#downstream-libraries), I propose moving the jobqueue config from https://github.com/NCAR/ncar-pangeo-tutorial/tree/master/config into ncar-jobqueue. This way, when ncar-jobqueue is installed, the config from ncar-jobqueue will be used to override dask-jobqueue's. 

Ccing @kmpaul

**Comment by matt-long** [comment]
@andersy005,  I agree with your suggestion.

Your bot is out of control! Rein it in!

**Comment by andersy005** [comment]
> Your bot is out of control! Rein it in! 

Indeed... A few days ago, it got stuck in a loop :). It is stable now though. 

I will open a separate PR specifically for the configuration issue
